### ISSUE TITLE
Full Screen / Accessing Left and Right Sidebar with hotkeys (Feature Request)

### ISSUE THREAD

**Issue by santiyounger** [Razumihin/obsidian-plugins#1]
Hey, thank you so much for creating this plugins. I'm a big fan of what you did with the full screen mode.

I can't wait for the official API to see this plug in get popular.

I wanted to know if it's possible to still access the left side pane and the right side pane via hotkeys.

If course having them hidden is great, so not showing them works great, but if hotkeys would still allow them to pop-up that would be amazing.

before discovering this plug in I used collapsible sidebar css
https://forum.obsidian.md/t/meta-post-common-css-hacks/1978/3

That one is limited in how full screen things go (it  doesn't hide the top bar with obsidian version)

but it does a great job at accessing the side bar with hotkeys, or by hovering mouse on top of side edges.

Thank you so much for your work, let me know if I screenshots or anything else is needed

**Comment by Razumihin** [comment]
Hi, 
That seems like a reasonable idea. 

I've been kind of waiting the official plugin support to arrive before writing any additional features, but i'll look if i could make sidebar hotkeys available when that happens.

**Comment by santiyounger** [comment]
Perfect looking forward for the official plug in support! Thanks for your work!
